version: '3'
services:

  db:
    image: postgres:14.2
    hostname: postgres-host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    image: quotation-metrics
    environment:
      - POSTGRES_HOST=postgres-host
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_SLLMODE=disable
      - POSTGRES_TIMEZONE=America/Sao_Paulo
      - BATCH_SIZE=1000
      - WORKERS=4
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db